version: "3.9"
services:
  postgres:
    container_name: demo-postgres
    image: postgres:14-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    restart: always
  redis:
    container_name: demo-redis
    image: redis:7-alpine
    ports:
      - 6379:6379
    restart: always

volumes:
  postgres-data:
    name: postgres-data